name: 🚀 Auto Deploy - Nuevos Programas
on:
  repository_dispatch:
    types: [wordpress-programa-nuevo]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write        # necesario para Cloudflare Pages
  id-token: write     # necesario para autenticación
  deployments: write  # necesario para crear deployments

env:
  NODE_ENV: production
  WORDPRESS_URL: ${{ vars.WORDPRESS_URL }}
  WP_USER: ${{ secrets.WP_USER }}
  WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

jobs:
  deploy-programas:
    name: 📺 Deploy con nuevo programa
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: 🧾 Context & env check
        run: |
          echo "event: ${{ github.event_name }} / action: ${{ github.event.action }}"
          node -v; npm -v
          echo "ENV present:"
          for v in WORDPRESS_URL WP_USER WP_APP_PASSWORD; do
            if [ -n "${!v}" ]; then echo "  ✓ $v"; else echo "  ✗ $v (VACÍO)"; fi
          done
          ls -la
      - name: 📦 Install dependencies
        run: npm ci --no-audit --no-fund
      - name: 🔨 Build project with new content
        env:
          CI: false   # evita fallos por warnings
        run: |
          set -euxo pipefail
          npm run build
      - name: 🗂 Detect dist folder
        id: dist
        run: |
          for d in dist build .output/public out; do
            if [ -d "$d" ]; then echo "dir=$d" >> $GITHUB_OUTPUT; exit 0; fi
          done
          echo "❌ No encuentro carpeta de salida"; exit 1
      - name: 🚀 Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: vinylstation
          directory: ${{ steps.dist.outputs.dir }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: 🧩 Upload npm log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            npm-debug.log
          if-no-files-found: ignore
